### PR TITLE
Rose st flour

### PR DESCRIPTION
**Pull request by egray523**
Integration of folder data, folder for Offenbach with metadata file, folder for Rose de Saint Flour with metadata file and TEI encoding.

### CODE REVIEW

**Review by rbbristow — APPROVED** [review]
Stunning.

**Review by rbbristow — CHANGES_REQUESTED** [review]
Dans tes "sp", la virgule est parfois dans la balise "speaker" et parfois dans la balise "stage".

But apart from that, your encoding is exquisite.

**Comment by egray523** [comment]
Should be fixed.

**Review by rbbristow — APPROVED** [review]
Delightful

**Review by rbbristow — APPROVED** [review]

**Pull request merged**
